\import type { Language } from "./types";

const en = {
  card: "My loyalty card",
  rewards: "My rewards",
  visits: "Visit history",
  how: "How it works",
  explore: "A LITTLE LOYALTY, A LOT OF AMORE",
  sidebarTitle: "A little Italy.\nRight here in Dammam.",
  sidebarCopy: "Good food brings us together.\nA little amore keeps us coming back.",
  install: "Add to home screen",
  staff: "Staff counter",
  guide: "Owner’s setup guide",
  join: "Join / log in",
  location: "Dammam, Saudi Arabia",
  header: "Welcome to the famiglia",
  hello: "Ciao",
  foodLover: "food lover",
  intro: "Your favorite Italian moments deserve a little something extra.",
  preview: "A taste of your future rewards · Preview",
  heroEyebrow: "THE ITALIANO BARI LOYALTY CLUB",
  heroLine1: "A little loyalty.",
  heroLine2: "A lot of amore.",
  heroCopy: "Collect stamps. Enjoy your favorites.\nLet us treat you along the way.",
  heroLink: "Good food. Even better rewards.",
  stampTitle: "Your stamp card",
  stampDescription: "Just {n} more stamps until a pizza on us!",
  complete: "Your pizza is on us. You’ve earned it!",
  stamps: "stamps collected",
  freeSide: "Free small pizza or pasta",
  freePizza: "Free pizza",
  everyVisit: "Every visit, a little closer.",
  sideReady: "Your 5-stamp reward is ready!",
  sideClaimed: "Free treat enjoyed. Next stop: main pizza!",
  keepGoing: "Your next delicious reward is getting closer.",
  viewReward: "View reward",
  qrTitle: "Your member QR",
  qrDesc: "A quick scan. A little more amore.",
  memberId: "MEMBER ID",
  expandQr: "Show at the counter",
  qrPreview: "Join to activate your personal QR",
  rewardTitle: "Good things are on the house",
  rewardSubtitle: "Little thank-yous, fresh from our kitchen.",
  viewAll: "All rewards",
  sideTitle: "Complete 4 orders, 5th order free!",
  sideDescription: "Free small pizza or pasta, it's your choice.",
  pizzaTitle: "The main event",
  pizzaDescription: "A free main pizza of your choice.",
  ready: "Ready to enjoy",
  toGo: "{n} stamps to go",
  redeemed: "Already enjoyed",
  footer: "Made with amore. Rewarded with every visit.",
  terms: "Loyalty terms",
  help: "Need a hand?",
  visitTitle: "Your delicious little journey",
  visitDescription: "Every stamp has a story. Here’s yours.",
  noVisits: "Your first delicious moment awaits",
  noVisitsDesc: "Visit Italiano Bari and show your member QR to collect your first stamp.",
  refresh: "Refresh card",
  howTitle: "More amore. Less effort.",
  howDesc: "No paper cards. No passwords. Just good food and great rewards.",
  step1: "Join the famiglia",
  step1desc: "Your name and mobile number are all you need. Joining is always free.",
  step2: "Visit. Eat. Collect.",
  step2desc: "Show your personal QR at the counter. Our team adds a stamp for your visit.",
  step3: "A little treat, on us",
  step3desc: "Enjoy a free small pizza or pasta at 5 stamps, and your favorite main pizza at 10.",
  joinTitle: "There’s a place for you here.",
  joinDescription: "Make your next Italian moment a little more rewarding.",
  joinButton: "Join the famiglia",
  loginTab: "Welcome back",
  name: "Your name",
  phone: "Mobile number",
  loginButton: "Find my card",
  close: "Close",
  previewNote: "This is a sample card. Your real card starts at 0 stamps.",
  privacy: "Phone lookup is not identity verification. Anyone with your number can view your card; only staff can change stamps or redeem rewards.",
  account: "Your membership",
  logout: "Log out",
  saved: "Your card is saved. Benvenuto!",
  memberSince: "Member since",
  qrHelp: "Ask our team to scan this code, or give them your mobile number. Only staff can add stamps and redeem rewards.",
  sampleHistory: "Join to start your own story",
  notAvailable: "A little patience, a lot of pizza.",
  rewardRule: "One reward of each kind per card. Our counter team will redeem it for you.",
  showQr: "Show my member QR",
  claimed: "You’ve enjoyed this reward on your current card.",
  sideRule: "Choose one small pizza or pasta. Redeeming this treat keeps all your stamps toward your free main pizza.",
  pizzaRule: "Choose a main pizza. Redeeming it uses 10 stamps and starts a new card. Any unclaimed 5-stamp reward on that card expires.",
};

const ar: typeof en = {
  card: "بطاقة الولاء",
  rewards: "مكافآتي",
  visits: "سجل الزيارات",
  how: "كيف يعمل البرنامج",
  explore: "قليل من الوفاء، كثير من المحبة",
  sidebarTitle: "قطعة من إيطاليا.\nهنا في الدمام.",
  sidebarCopy: "الطعام اللذيذ يجمعنا.\nوالمحبة تجعلنا نعود.",
  install: "أضف إلى الشاشة الرئيسية",
  staff: "لوحة الموظفين",
  guide: "دليل الإعداد",
  join: "انضم / تسجيل الدخول",
  location: "الدمام، السعودية",
  header: "أهلاً بك في العائلة",
  hello: "أهلاً",
  foodLover: "عاشق المذاق",
  intro: "لحظاتك الإيطالية المفضلة تستحق المزيد.",
  preview: "لمحة عن مكافآ
