import data from "./menu-data.json";
import type { Language } from "./types";

export type MenuCategory = "pizza" | "pasta" | "salad" | "drinks";
export type MenuFilter = MenuCategory | "all" | "saved";
export type MenuPrice = { size: string; sizeAr: string; price: number; oldPrice: number | null };
export type MenuItem = { id: string; category: MenuCategory; name: string; nameAr: string; note: string; noteAr: string; badge: string; prices: MenuPrice[]; image: string | null };
export const menuItems = data.items as MenuItem[];
export const menuSource = data.sourceUrl;
export const restaurantLinks = {
  location: data.links.find((link) => link.name === "Location")!.url,
  instagram: data.links.find((link) => link.name === "Instagram")!.url,
  tiktok: data.links.find((link) => link.name === "TikTok")!.url,
};
export const menuCategories: { id: MenuCategory; name: string; nameAr: string; caption: string }[] = [
  { id: "pizza", name: "Pizza", nameAr: "البيتزا", caption: "A little slice of happiness." },
  { id: "pasta", name: "Pasta", nameAr: "الباستا", caption: "Comfort, the Italian way." },
  { id: "salad", name: "Salads & sides", nameAr: "السلطات", caption: "A little something on the side." },
  { id: "drinks", name: "Drinks", nameAr: "المشروبات", caption: "The perfect finishing touch." },
];
const en = {
  nav: "Our menu", heroKicker: "TRATTORIA · مطعم إيطالي", heroFirst: "A little Italy.", heroSecond: "A lot of flavour.", heroDescription: "Your favourite pizzas, comforting pastas, and little extras. Made with amore, right here in Dammam.", explore: "Explore the menu", heroTag: "BUON APPETITO", special: "NEW SPECIAL", from: "FROM", loyaltyTitle: "Good taste deserves great rewards.", loyaltyDescription: "5 stamps. A little treat. 10 stamps. A pizza on us.", loyaltyButton: "My loyalty card", sectionTitle: "Something delicious awaits.", sectionDescription: "Find your favourite. Or fall for something new.", search: "Find a dish…", searchLabel: "Search menu by dish name", all: "All dishes", saved: "Favourites", pizza: "Pizza", pasta: "Pasta", salad: "Salads & sides", drinks: "Drinks", clearSearch: "Clear search", savedTitle: "Your little list of favourites.", savedDescription: "Saved on this device, ready for your next visit.", result: "dishes", view: "View dish", selectSize: "Choose your size", regular: "Regular", small: "Small", large: "Large", spicy: "Spicy / non-spicy", save: "Save to favourites", unsave: "Remove from favourites", savedToast: "Saved to your favourites.", removedToast: "Removed from your favourites.", savedDevice: "Your favourites are saved on this device.", emptyTitle: "Not on the menu. Yet.", emptyDescription: "Try another dish name, in English or Arabic, or explore all our favourites.", emptySaved: "A little room for your favourites.", emptySavedDescription: "Tap the heart on any dish to save it here for your next visit.", reset: "Explore all dishes", houseNote: "A little note from our kitchen", availability: "Ask our team about ingredients, allergens, and availability before ordering. Prices shown are from our published menu.", priceNote: "Prices in Saudi riyals (SR). Please confirm availability at the counter.", detailNote: "This is our dine-in menu. Speak with our team at the counter to place your order.", bottomTitle: "Come for the food.", bottomSecond: "Stay for the famiglia.", bottomDescription: "Your next Italian moment is waiting. Find us in Dammam, or join our loyalty club before you visit.", directions: "Find our restaurant", join: "Join the famiglia", footer: "From Bari, with amore. Here in Dammam.", original: "Original menu", share: "Share menu", copied: "Menu link copied. Share a little amore!", copyError: "Copy isn’t available. You can share the address from your browser.", imageCaption: "A closer look",
};
const ar: typeof en = {
  nav: "قائمة الطعام", heroKicker: "TRATTORIA · مطعم إيطالي", heroFirst: "قطعة من إيطاليا.", heroSecond: "الكثير من المذاق.", heroDescription: "بيتزا مفضلة، باستا شهية، وإضافات لذيذة. نصنعها بكل حب، هنا في الدمام.", explore: "اكتشف القائمة", heroTag: "بالعافية", special: "جديد ومميز", from: "ابتداءً من", loyaltyTitle: "المذاق الرائع يستحق مكافآت رائعة.", loyaltyDescription: "٥ أختام لهدية صغيرة. ١٠ أختام لبيتزا على حسابنا.", loyaltyButton: "بطاقة الولاء", sectionTitle: "شيء لذيذ بانتظارك.", sectionDescription: "اختر المفضل لديك. أو اكتشف مذاقاً جديداً.", search: "ابحث عن طبق…", searchLabel: "ابحث في القائمة باسم الطبق", all: "كل الأطباق", saved: "المفضلة", pizza: "بيتزا", pasta: "باستا", salad: "سلطات وإضافات", drinks: "مشروبات", clearSearch: "مسح البحث", savedTitle: "قائمتك الصغيرة من الأطباق المفضلة.", savedDescription: "محفوظة على هذا الجهاز، لزيارتك القادمة.", result: "أطباق", view: "عرض الطبق", selectSize: "اختر الحجم", regular: "عادي", small: "صغير", large: "كبير", spicy: "حار / غير حار", save: "أضف إلى المفضلة", unsave: "إزالة من المفضلة", savedToast: "تمت الإضافة إلى المفضلة.", removedToast: "تمت الإزالة من المفضلة.", savedDevice: "مفضلتك محفوظة على هذا الجهاز.", emptyTitle: "لم نجد هذا الطبق.", emptyDescription: "جرّب اسماً آخر بالعربية أو الإنجليزية، أو اكتشف جميع أطباقنا.", emptySaved: "مكان صغير لأطباقك المفضلة.", emptySavedDescription: "اضغط على القلب لحفظ أي طبق هنا لزيارتك القادمة.", reset: "اكتشف كل الأطباق", houseNote: "ملاحظة من مطبخنا", availability: "اسأل فريقنا عن المكونات ومسببات الحساسية والتوفر قبل الطلب. الأسعار المعروضة من قائمتنا المنشورة.", priceNote: "الأسعار بالريال السعودي. يرجى التأكد من التوفر عند الكاشير.", detailNote: "هذه قائمة المطعم. تحدث مع فريقنا عند الكاشير لتقديم طلبك.", bottomTitle: "تعال من أجل المذاق.", bottomSecond: "وابقَ مع العائلة.", bottomDescription: "لحظتك الإيطالية القادمة بانتظارك. زرنا في الدمام أو انضم إلى برنامج الولاء قبل زيارتك.", directions: "موقع المطعم", join: "انضم إلى العائلة", footer: "من باري بكل حب. هنا في الدمام.", original: "القائمة الأصلية", share: "مشاركة القائمة", copied: "تم نسخ رابط القائمة. شارك المحبة!", copyError: "تعذّر النسخ. يمكنك مشاركة الرابط من متصفحك.", imageCaption: "نظرة أقرب",
};
const ur: typeof en = {
  ...en, nav: "ہمارا مینو", heroFirst: "اٹلی کی ایک جھلک۔", heroSecond: "ذائقہ بھرپور۔", heroDescription: "آپ کے پسندیدہ پیزا، مزیدار پاستا اور چھوٹے تحفے۔ دمام میں، محبت سے تیار۔", explore: "مینو دیکھیں", special: "نیا اسپیشل", from: "قیمت شروع", loyaltyTitle: "اچھے ذائقے کے ساتھ بہترین انعامات۔", loyaltyDescription: "۵ اسٹیمپ پر تحفہ۔ ۱۰ اسٹیمپ پر پیزا ہماری طرف سے۔", loyaltyButton: "میرا لائلٹی کارڈ", sectionTitle: "کچھ مزیدار آپ کا منتظر ہے۔", sectionDescription: "اپنا پسندیدہ چنیں۔ یا کچھ نیا آزمائیں۔", search: "کوئی ڈش تلاش کریں…", searchLabel: "مینو میں ڈش تلاش کریں", all: "تمام پکوان", saved: "پسندیدہ", pizza: "پیزا", pasta: "پاستا", salad: "سلاد اور سائیڈز", drinks: "مشروبات", clearSearch: "تلاش صاف کریں", savedTitle: "آپ کی پسندیدہ ڈشز۔", savedDescription: "اس ڈیوائس پر محفوظ، آپ کی اگلی آمد کے لیے۔", result: "پکوان", view: "ڈش دیکھیں", selectSize: "سائز منتخب کریں", regular: "ریگولر", small: "چھوٹا", large: "بڑا", spicy: "تیز مصالحہ / بغیر تیز مصالحے", save: "پسندیدہ میں محفوظ کریں", unsave: "پسندیدہ سے ہٹائیں", savedToast: "پسندیدہ میں محفوظ ہو گیا۔", removedToast: "پسندیدہ سے ہٹا دیا گیا۔", savedDevice: "آپ کی پسند اس ڈیوائس پر محفوظ ہے۔", emptyTitle: "یہ ڈش نہیں ملی۔", emptyDescription: "انگریزی یا عربی میں دوسرا نام تلاش کریں۔", emptySaved: "آپ کی پسند کا انتظار ہے۔", emptySavedDescription: "ڈش پر دل دبائیں اور اگلی آمد کے لیے محفوظ کریں۔", reset: "تمام پکوان دیکھیں", houseNote: "ہمارے کچن کی طرف سے ایک بات", availability: "اجزاء، الرجی اور دستیابی کے بارے میں آرڈر سے پہلے ہماری ٹیم سے پوچھیں۔ قیمتیں ہمارے شائع شدہ مینو سے ہیں۔", priceNote: "قیمتیں سعودی ریال میں ہیں۔ دستیابی کاؤنٹر پر معلوم کریں۔", detailNote: "یہ ریسٹورنٹ کا مینو ہے۔ آرڈر کے لیے کاؤنٹر پر ہماری ٹیم سے بات کریں۔", bottomTitle: "ذائقے کے لیے آئیں۔", bottomSecond: "خاندان کا حصہ بن جائیں۔", bottomDescription: "آپ کا اگلا اطالوی لمحہ منتظر ہے۔ دمام میں ہم سے ملیں یا ہمارے لائلٹی کلب میں شامل ہوں۔", directions: "ریسٹورنٹ کا مقام", join: "خاندان میں شامل ہوں", footer: "باری سے محبت کے ساتھ۔ دمام میں۔", original: "اصل مینو", share: "مینو شیئر کریں", copied: "مینو کا لنک کاپی ہو گیا۔", copyError: "کاپی دستیاب نہیں۔ براؤزر کا لنک شیئر کریں۔",
};
const hi: typeof en = {
  ...en, nav: "हमारा मेन्यू", heroFirst: "इटली की एक झलक।", heroSecond: "ढेर सारा स्वाद।", heroDescription: "पसंदीदा पिज़्ज़ा, स्वादिष्ट पास्ता और छोटी खुशियाँ। दम्माम में, प्यार से तैयार।", explore: "मेन्यू देखें", special: "नया स्पेशल", from: "शुरुआती कीमत", loyaltyTitle: "अच्छे स्वाद के साथ शानदार इनाम।", loyaltyDescription: "५ स्टैम्प पर तोहफ़ा। १० पर पिज़्ज़ा हमारी ओर से।", loyaltyButton: "मेरा लॉयल्टी कार्ड", sectionTitle: "कुछ स्वादिष्ट आपका इंतज़ार कर रहा है।", sectionDescription: "अपना पसंदीदा चुनें। या कुछ नया आज़माएँ।", search: "कोई डिश खोजें…", searchLabel: "मेन्यू में डिश खोजें", all: "सभी व्यंजन", saved: "पसंदीदा", pizza: "पिज़्ज़ा", pasta: "पास्ता", salad: "सलाद और साइड्स", drinks: "पेय", clearSearch: "खोज मिटाएँ", savedTitle: "आपकी पसंदीदा डिशेज़।", savedDescription: "इस डिवाइस पर सुरक्षित, आपकी अगली विज़िट के लिए।", result: "व्यंजन", view: "डिश देखें", selectSize: "साइज़ चुनें", regular: "रेगुलर", small: "छोटा", large: "बड़ा", spicy: "तीखा / बिना तीखे के", save: "पसंदीदा में सेव करें", unsave: "पसंदीदा से हटाएँ", savedToast: "पसंदीदा में सेव हो गया।", removedToast: "पसंदीदा से हटा दिया गया।", savedDevice: "आपकी पसंद इस डिवाइस पर सेव है।", emptyTitle: "यह डिश नहीं मिली।", emptyDescription: "अंग्रेज़ी या अरबी में कोई दूसरा नाम खोजें।", emptySaved: "आपकी पसंद का इंतज़ार है।", emptySavedDescription: "किसी डिश पर दिल दबाकर उसे अगली विज़िट के लिए सेव करें।", reset: "सभी व्यंजन देखें", houseNote: "हमारी रसोई से एक छोटी बात", availability: "ऑर्डर से पहले सामग्री, एलर्जी और उपलब्धता के बारे में हमारी टीम से पूछें। कीमतें हमारे प्रकाशित मेन्यू से हैं।", priceNote: "कीमतें सऊदी रियाल में हैं। उपलब्धता काउंटर पर पूछें।", detailNote: "यह रेस्टोरेंट का मेन्यू है। ऑर्डर देने के लिए काउंटर पर हमारी टीम से बात करें।", bottomTitle: "स्वाद के लिए आएँ।", bottomSecond: "परिवार का हिस्सा बन जाएँ।", bottomDescription: "आपका अगला इटैलियन पल आपका इंतज़ार कर रहा है। दम्माम में हमसे मिलें या लॉयल्टी क्लब से जुड़ें।", directions: "रेस्टोरेंट का पता", join: "परिवार से जुड़ें", footer: "बारी से प्यार के साथ। दम्माम में।", original: "मूल मेन्यू", share: "मेन्यू शेयर करें", copied: "मेन्यू लिंक कॉपी हो गया।", copyError: "कॉपी उपलब्ध नहीं है। ब्राउज़र का लिंक शेयर करें।",
};
export const menuCopy: Record<Language, typeof en> = { en, ar, ur, hi };
export function normalizeMenuSearch(text: string) { return text.toLocaleLowerCase().normalize("NFKD").replace(/[\u064B-\u065F\u0670]/g, "").replace(/[أإآ]/g, "ا").replace(/ى/g, "ي").trim(); }
export function validMenuFilter(value?: string): MenuFilter { return ["all", "saved", "pizza", "pasta", "salad", "drinks"].includes(value || "") ? value as MenuFilter : "all"; }
